version: '3'

services:

  text-mining-dev:
    build: .
    ports:
      - "2222:22"
    links:
      - db-testing:db-host
    volumes:
      - ./data/assets:/root/data

  text-mining-prod:
    build: .
    ports:
      - "55555:22"
    links:
      - db-production:db-host
    volumes:
      - ./data/assets:/root/data

  db-testing:
    image: "postgres:alpine"
    volumes:
      - ./data/postgres/testing:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 8001:5432

  db-production:
    image: "postgres:alpine"
    volumes:
      - ./data/postgres/production:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: production
      POSTGRES_PASSWORD: production
    ports:
      - 8002:5432
