database:
  host: db-host
  port: 5432
  dbname: postgres
  user: user
  password: password

guardian_csv:
  articles: filepath
  authors: filepath
  comments: filepath

embeddings:
  glove: filepath

models:
  doc2vec_dir: filepath

guardian_api:
  keys: ['test']

training_results:
  root_dir: dirpath

training_parameters:
  default:
    batch_size: 64
    epochs: 50
    dictionary_size: 40000
    max_headline_length: 20
    body_begin_length: 50
    max_article_length: 20000
    headline_doc2vec_dimensions: 50
    article_doc2vec_dimensions: 300
  choices:
    headline_doc2vec_dimensions: [50, 100, 300]
    article_doc2vec_dimensions: [50, 100, 300]
