database:
  host: db-host
  port: 5432
  dbname: postgres
  user: user
  password: password

guardian-csv:
  articles: filepath
  authors: filepath
  comments: filepath

embeddings:
  glove: filepath

models:
  doc2vec_dir: filepath

guardian-api:
  keys: ['test']

training-results:
  doc2vec_model: filepath
  headline_model: filepath
  headline_model: filepath